# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mannschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'mannschaften',
            },
        ),
        migrations.CreateModel(
            name='Runde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'V1', b'Vorrunde, Spieltag 1'), (b'V2', b'Vorrunde, Spieltag 2'), (b'V3', b'Vorrunde, Spieltag 3'), (b'AF', b'Achtelfinale'), (b'VF', b'Viertelfinale'), (b'HF', b'Halbfinale'), (b'F', b'Finale')], max_length=2, unique=True)),
                ('faktor', models.IntegerField(default=1)),
                ('freigabe', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Runden',
            },
        ),
        migrations.CreateModel(
            name='Spiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tore1', models.IntegerField(blank=True, null=True)),
                ('tore2', models.IntegerField(blank=True, null=True)),
                ('datum', models.DateTimeField()),
                ('mannschaft1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms1', to='tipps.Mannschaft')),
                ('mannschaft2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms2', to='tipps.Mannschaft')),
                ('runde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipps.Runde')),
            ],
            options={
                'verbose_name_plural': 'Spiele',
            },
        ),
        migrations.CreateModel(
            name='Tipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tore1', models.IntegerField()),
                ('tore2', models.IntegerField()),
                ('punkte', models.IntegerField()),
                ('spiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipps.Spiel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[(b'bn', b'Bonn'), (b'da', b'Darmstadt'), (b'es', b'Essen'), (b'pdb', b'Paderborn'), (b'mz', b'Mainz'), (b'wu', b'Wuppertal')], max_length=3)),
                ('punkte', models.IntegerField()),
                ('platz', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(to='tipps.Userdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tipp',
            unique_together=set([('user', 'spiel')]),
        ),
        migrations.AlterUniqueTogether(
            name='spiel',
            unique_together=set([('mannschaft1', 'mannschaft2', 'datum')]),
        ),
    ]
