# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, to='tipps.Userdata'),
        ),
    ]
